# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wouter/Documents/School/SysteemBasis/csd_proj/chess-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wouter/Documents/School/SysteemBasis/csd_proj/chess-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wouter/Documents/School/SysteemBasis/csd_proj/chess-engine/CMakeFiles /Users/wouter/Documents/School/SysteemBasis/csd_proj/chess-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wouter/Documents/School/SysteemBasis/csd_proj/chess-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess-engine-test

# Build rule for target.
chess-engine-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess-engine-test
.PHONY : chess-engine-test

# fast build rule for target.
chess-engine-test/fast:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/build
.PHONY : chess-engine-test/fast

#=============================================================================
# Target rules for targets named chess-engine

# Build rule for target.
chess-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess-engine
.PHONY : chess-engine

# fast build rule for target.
chess-engine/fast:
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/build
.PHONY : chess-engine/fast

#=============================================================================
# Target rules for targets named tiny-osc-test

# Build rule for target.
tiny-osc-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiny-osc-test
.PHONY : tiny-osc-test

# fast build rule for target.
tiny-osc-test/fast:
	$(MAKE) -f CMakeFiles/tiny-osc-test.dir/build.make CMakeFiles/tiny-osc-test.dir/build
.PHONY : tiny-osc-test/fast

#=============================================================================
# Target rules for targets named tiny_osc

# Build rule for target.
tiny_osc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiny_osc
.PHONY : tiny_osc

# fast build rule for target.
tiny_osc/fast:
	$(MAKE) -f CMakeFiles/tiny_osc.dir/build.make CMakeFiles/tiny_osc.dir/build
.PHONY : tiny_osc/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shallow-blue-fork/src/attacks.o: src/shallow-blue-fork/src/attacks.cc.o

.PHONY : src/shallow-blue-fork/src/attacks.o

# target to build an object file
src/shallow-blue-fork/src/attacks.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/attacks.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/attacks.cc.o
.PHONY : src/shallow-blue-fork/src/attacks.cc.o

src/shallow-blue-fork/src/attacks.i: src/shallow-blue-fork/src/attacks.cc.i

.PHONY : src/shallow-blue-fork/src/attacks.i

# target to preprocess a source file
src/shallow-blue-fork/src/attacks.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/attacks.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/attacks.cc.i
.PHONY : src/shallow-blue-fork/src/attacks.cc.i

src/shallow-blue-fork/src/attacks.s: src/shallow-blue-fork/src/attacks.cc.s

.PHONY : src/shallow-blue-fork/src/attacks.s

# target to generate assembly for a file
src/shallow-blue-fork/src/attacks.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/attacks.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/attacks.cc.s
.PHONY : src/shallow-blue-fork/src/attacks.cc.s

src/shallow-blue-fork/src/board.o: src/shallow-blue-fork/src/board.cc.o

.PHONY : src/shallow-blue-fork/src/board.o

# target to build an object file
src/shallow-blue-fork/src/board.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/board.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/board.cc.o
.PHONY : src/shallow-blue-fork/src/board.cc.o

src/shallow-blue-fork/src/board.i: src/shallow-blue-fork/src/board.cc.i

.PHONY : src/shallow-blue-fork/src/board.i

# target to preprocess a source file
src/shallow-blue-fork/src/board.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/board.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/board.cc.i
.PHONY : src/shallow-blue-fork/src/board.cc.i

src/shallow-blue-fork/src/board.s: src/shallow-blue-fork/src/board.cc.s

.PHONY : src/shallow-blue-fork/src/board.s

# target to generate assembly for a file
src/shallow-blue-fork/src/board.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/board.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/board.cc.s
.PHONY : src/shallow-blue-fork/src/board.cc.s

src/shallow-blue-fork/src/book.o: src/shallow-blue-fork/src/book.cc.o

.PHONY : src/shallow-blue-fork/src/book.o

# target to build an object file
src/shallow-blue-fork/src/book.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/book.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/book.cc.o
.PHONY : src/shallow-blue-fork/src/book.cc.o

src/shallow-blue-fork/src/book.i: src/shallow-blue-fork/src/book.cc.i

.PHONY : src/shallow-blue-fork/src/book.i

# target to preprocess a source file
src/shallow-blue-fork/src/book.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/book.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/book.cc.i
.PHONY : src/shallow-blue-fork/src/book.cc.i

src/shallow-blue-fork/src/book.s: src/shallow-blue-fork/src/book.cc.s

.PHONY : src/shallow-blue-fork/src/book.s

# target to generate assembly for a file
src/shallow-blue-fork/src/book.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/book.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/book.cc.s
.PHONY : src/shallow-blue-fork/src/book.cc.s

src/shallow-blue-fork/src/eval.o: src/shallow-blue-fork/src/eval.cc.o

.PHONY : src/shallow-blue-fork/src/eval.o

# target to build an object file
src/shallow-blue-fork/src/eval.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/eval.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/eval.cc.o
.PHONY : src/shallow-blue-fork/src/eval.cc.o

src/shallow-blue-fork/src/eval.i: src/shallow-blue-fork/src/eval.cc.i

.PHONY : src/shallow-blue-fork/src/eval.i

# target to preprocess a source file
src/shallow-blue-fork/src/eval.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/eval.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/eval.cc.i
.PHONY : src/shallow-blue-fork/src/eval.cc.i

src/shallow-blue-fork/src/eval.s: src/shallow-blue-fork/src/eval.cc.s

.PHONY : src/shallow-blue-fork/src/eval.s

# target to generate assembly for a file
src/shallow-blue-fork/src/eval.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/eval.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/eval.cc.s
.PHONY : src/shallow-blue-fork/src/eval.cc.s

src/shallow-blue-fork/src/generalmovepicker.o: src/shallow-blue-fork/src/generalmovepicker.cc.o

.PHONY : src/shallow-blue-fork/src/generalmovepicker.o

# target to build an object file
src/shallow-blue-fork/src/generalmovepicker.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/generalmovepicker.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/generalmovepicker.cc.o
.PHONY : src/shallow-blue-fork/src/generalmovepicker.cc.o

src/shallow-blue-fork/src/generalmovepicker.i: src/shallow-blue-fork/src/generalmovepicker.cc.i

.PHONY : src/shallow-blue-fork/src/generalmovepicker.i

# target to preprocess a source file
src/shallow-blue-fork/src/generalmovepicker.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/generalmovepicker.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/generalmovepicker.cc.i
.PHONY : src/shallow-blue-fork/src/generalmovepicker.cc.i

src/shallow-blue-fork/src/generalmovepicker.s: src/shallow-blue-fork/src/generalmovepicker.cc.s

.PHONY : src/shallow-blue-fork/src/generalmovepicker.s

# target to generate assembly for a file
src/shallow-blue-fork/src/generalmovepicker.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/generalmovepicker.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/generalmovepicker.cc.s
.PHONY : src/shallow-blue-fork/src/generalmovepicker.cc.s

src/shallow-blue-fork/src/main.o: src/shallow-blue-fork/src/main.cc.o

.PHONY : src/shallow-blue-fork/src/main.o

# target to build an object file
src/shallow-blue-fork/src/main.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/main.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/main.cc.o
.PHONY : src/shallow-blue-fork/src/main.cc.o

src/shallow-blue-fork/src/main.i: src/shallow-blue-fork/src/main.cc.i

.PHONY : src/shallow-blue-fork/src/main.i

# target to preprocess a source file
src/shallow-blue-fork/src/main.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/main.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/main.cc.i
.PHONY : src/shallow-blue-fork/src/main.cc.i

src/shallow-blue-fork/src/main.s: src/shallow-blue-fork/src/main.cc.s

.PHONY : src/shallow-blue-fork/src/main.s

# target to generate assembly for a file
src/shallow-blue-fork/src/main.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/main.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/main.cc.s
.PHONY : src/shallow-blue-fork/src/main.cc.s

src/shallow-blue-fork/src/move.o: src/shallow-blue-fork/src/move.cc.o

.PHONY : src/shallow-blue-fork/src/move.o

# target to build an object file
src/shallow-blue-fork/src/move.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/move.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/move.cc.o
.PHONY : src/shallow-blue-fork/src/move.cc.o

src/shallow-blue-fork/src/move.i: src/shallow-blue-fork/src/move.cc.i

.PHONY : src/shallow-blue-fork/src/move.i

# target to preprocess a source file
src/shallow-blue-fork/src/move.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/move.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/move.cc.i
.PHONY : src/shallow-blue-fork/src/move.cc.i

src/shallow-blue-fork/src/move.s: src/shallow-blue-fork/src/move.cc.s

.PHONY : src/shallow-blue-fork/src/move.s

# target to generate assembly for a file
src/shallow-blue-fork/src/move.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/move.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/move.cc.s
.PHONY : src/shallow-blue-fork/src/move.cc.s

src/shallow-blue-fork/src/movegen.o: src/shallow-blue-fork/src/movegen.cc.o

.PHONY : src/shallow-blue-fork/src/movegen.o

# target to build an object file
src/shallow-blue-fork/src/movegen.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movegen.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movegen.cc.o
.PHONY : src/shallow-blue-fork/src/movegen.cc.o

src/shallow-blue-fork/src/movegen.i: src/shallow-blue-fork/src/movegen.cc.i

.PHONY : src/shallow-blue-fork/src/movegen.i

# target to preprocess a source file
src/shallow-blue-fork/src/movegen.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movegen.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movegen.cc.i
.PHONY : src/shallow-blue-fork/src/movegen.cc.i

src/shallow-blue-fork/src/movegen.s: src/shallow-blue-fork/src/movegen.cc.s

.PHONY : src/shallow-blue-fork/src/movegen.s

# target to generate assembly for a file
src/shallow-blue-fork/src/movegen.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movegen.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movegen.cc.s
.PHONY : src/shallow-blue-fork/src/movegen.cc.s

src/shallow-blue-fork/src/movepicker.o: src/shallow-blue-fork/src/movepicker.cc.o

.PHONY : src/shallow-blue-fork/src/movepicker.o

# target to build an object file
src/shallow-blue-fork/src/movepicker.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movepicker.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movepicker.cc.o
.PHONY : src/shallow-blue-fork/src/movepicker.cc.o

src/shallow-blue-fork/src/movepicker.i: src/shallow-blue-fork/src/movepicker.cc.i

.PHONY : src/shallow-blue-fork/src/movepicker.i

# target to preprocess a source file
src/shallow-blue-fork/src/movepicker.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movepicker.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movepicker.cc.i
.PHONY : src/shallow-blue-fork/src/movepicker.cc.i

src/shallow-blue-fork/src/movepicker.s: src/shallow-blue-fork/src/movepicker.cc.s

.PHONY : src/shallow-blue-fork/src/movepicker.s

# target to generate assembly for a file
src/shallow-blue-fork/src/movepicker.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/movepicker.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/movepicker.cc.s
.PHONY : src/shallow-blue-fork/src/movepicker.cc.s

src/shallow-blue-fork/src/option.o: src/shallow-blue-fork/src/option.cc.o

.PHONY : src/shallow-blue-fork/src/option.o

# target to build an object file
src/shallow-blue-fork/src/option.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/option.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/option.cc.o
.PHONY : src/shallow-blue-fork/src/option.cc.o

src/shallow-blue-fork/src/option.i: src/shallow-blue-fork/src/option.cc.i

.PHONY : src/shallow-blue-fork/src/option.i

# target to preprocess a source file
src/shallow-blue-fork/src/option.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/option.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/option.cc.i
.PHONY : src/shallow-blue-fork/src/option.cc.i

src/shallow-blue-fork/src/option.s: src/shallow-blue-fork/src/option.cc.s

.PHONY : src/shallow-blue-fork/src/option.s

# target to generate assembly for a file
src/shallow-blue-fork/src/option.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/option.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/option.cc.s
.PHONY : src/shallow-blue-fork/src/option.cc.s

src/shallow-blue-fork/src/orderinginfo.o: src/shallow-blue-fork/src/orderinginfo.cc.o

.PHONY : src/shallow-blue-fork/src/orderinginfo.o

# target to build an object file
src/shallow-blue-fork/src/orderinginfo.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/orderinginfo.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/orderinginfo.cc.o
.PHONY : src/shallow-blue-fork/src/orderinginfo.cc.o

src/shallow-blue-fork/src/orderinginfo.i: src/shallow-blue-fork/src/orderinginfo.cc.i

.PHONY : src/shallow-blue-fork/src/orderinginfo.i

# target to preprocess a source file
src/shallow-blue-fork/src/orderinginfo.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/orderinginfo.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/orderinginfo.cc.i
.PHONY : src/shallow-blue-fork/src/orderinginfo.cc.i

src/shallow-blue-fork/src/orderinginfo.s: src/shallow-blue-fork/src/orderinginfo.cc.s

.PHONY : src/shallow-blue-fork/src/orderinginfo.s

# target to generate assembly for a file
src/shallow-blue-fork/src/orderinginfo.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/orderinginfo.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/orderinginfo.cc.s
.PHONY : src/shallow-blue-fork/src/orderinginfo.cc.s

src/shallow-blue-fork/src/pawnstructuretable.o: src/shallow-blue-fork/src/pawnstructuretable.cc.o

.PHONY : src/shallow-blue-fork/src/pawnstructuretable.o

# target to build an object file
src/shallow-blue-fork/src/pawnstructuretable.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.o
.PHONY : src/shallow-blue-fork/src/pawnstructuretable.cc.o

src/shallow-blue-fork/src/pawnstructuretable.i: src/shallow-blue-fork/src/pawnstructuretable.cc.i

.PHONY : src/shallow-blue-fork/src/pawnstructuretable.i

# target to preprocess a source file
src/shallow-blue-fork/src/pawnstructuretable.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.i
.PHONY : src/shallow-blue-fork/src/pawnstructuretable.cc.i

src/shallow-blue-fork/src/pawnstructuretable.s: src/shallow-blue-fork/src/pawnstructuretable.cc.s

.PHONY : src/shallow-blue-fork/src/pawnstructuretable.s

# target to generate assembly for a file
src/shallow-blue-fork/src/pawnstructuretable.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/pawnstructuretable.cc.s
.PHONY : src/shallow-blue-fork/src/pawnstructuretable.cc.s

src/shallow-blue-fork/src/psquaretable.o: src/shallow-blue-fork/src/psquaretable.cc.o

.PHONY : src/shallow-blue-fork/src/psquaretable.o

# target to build an object file
src/shallow-blue-fork/src/psquaretable.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/psquaretable.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/psquaretable.cc.o
.PHONY : src/shallow-blue-fork/src/psquaretable.cc.o

src/shallow-blue-fork/src/psquaretable.i: src/shallow-blue-fork/src/psquaretable.cc.i

.PHONY : src/shallow-blue-fork/src/psquaretable.i

# target to preprocess a source file
src/shallow-blue-fork/src/psquaretable.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/psquaretable.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/psquaretable.cc.i
.PHONY : src/shallow-blue-fork/src/psquaretable.cc.i

src/shallow-blue-fork/src/psquaretable.s: src/shallow-blue-fork/src/psquaretable.cc.s

.PHONY : src/shallow-blue-fork/src/psquaretable.s

# target to generate assembly for a file
src/shallow-blue-fork/src/psquaretable.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/psquaretable.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/psquaretable.cc.s
.PHONY : src/shallow-blue-fork/src/psquaretable.cc.s

src/shallow-blue-fork/src/qsearchmovepicker.o: src/shallow-blue-fork/src/qsearchmovepicker.cc.o

.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.o

# target to build an object file
src/shallow-blue-fork/src/qsearchmovepicker.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.o
.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.cc.o

src/shallow-blue-fork/src/qsearchmovepicker.i: src/shallow-blue-fork/src/qsearchmovepicker.cc.i

.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.i

# target to preprocess a source file
src/shallow-blue-fork/src/qsearchmovepicker.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.i
.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.cc.i

src/shallow-blue-fork/src/qsearchmovepicker.s: src/shallow-blue-fork/src/qsearchmovepicker.cc.s

.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.s

# target to generate assembly for a file
src/shallow-blue-fork/src/qsearchmovepicker.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/qsearchmovepicker.cc.s
.PHONY : src/shallow-blue-fork/src/qsearchmovepicker.cc.s

src/shallow-blue-fork/src/rays.o: src/shallow-blue-fork/src/rays.cc.o

.PHONY : src/shallow-blue-fork/src/rays.o

# target to build an object file
src/shallow-blue-fork/src/rays.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/rays.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/rays.cc.o
.PHONY : src/shallow-blue-fork/src/rays.cc.o

src/shallow-blue-fork/src/rays.i: src/shallow-blue-fork/src/rays.cc.i

.PHONY : src/shallow-blue-fork/src/rays.i

# target to preprocess a source file
src/shallow-blue-fork/src/rays.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/rays.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/rays.cc.i
.PHONY : src/shallow-blue-fork/src/rays.cc.i

src/shallow-blue-fork/src/rays.s: src/shallow-blue-fork/src/rays.cc.s

.PHONY : src/shallow-blue-fork/src/rays.s

# target to generate assembly for a file
src/shallow-blue-fork/src/rays.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/rays.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/rays.cc.s
.PHONY : src/shallow-blue-fork/src/rays.cc.s

src/shallow-blue-fork/src/search.o: src/shallow-blue-fork/src/search.cc.o

.PHONY : src/shallow-blue-fork/src/search.o

# target to build an object file
src/shallow-blue-fork/src/search.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/search.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/search.cc.o
.PHONY : src/shallow-blue-fork/src/search.cc.o

src/shallow-blue-fork/src/search.i: src/shallow-blue-fork/src/search.cc.i

.PHONY : src/shallow-blue-fork/src/search.i

# target to preprocess a source file
src/shallow-blue-fork/src/search.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/search.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/search.cc.i
.PHONY : src/shallow-blue-fork/src/search.cc.i

src/shallow-blue-fork/src/search.s: src/shallow-blue-fork/src/search.cc.s

.PHONY : src/shallow-blue-fork/src/search.s

# target to generate assembly for a file
src/shallow-blue-fork/src/search.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/search.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/search.cc.s
.PHONY : src/shallow-blue-fork/src/search.cc.s

src/shallow-blue-fork/src/transptable.o: src/shallow-blue-fork/src/transptable.cc.o

.PHONY : src/shallow-blue-fork/src/transptable.o

# target to build an object file
src/shallow-blue-fork/src/transptable.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/transptable.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/transptable.cc.o
.PHONY : src/shallow-blue-fork/src/transptable.cc.o

src/shallow-blue-fork/src/transptable.i: src/shallow-blue-fork/src/transptable.cc.i

.PHONY : src/shallow-blue-fork/src/transptable.i

# target to preprocess a source file
src/shallow-blue-fork/src/transptable.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/transptable.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/transptable.cc.i
.PHONY : src/shallow-blue-fork/src/transptable.cc.i

src/shallow-blue-fork/src/transptable.s: src/shallow-blue-fork/src/transptable.cc.s

.PHONY : src/shallow-blue-fork/src/transptable.s

# target to generate assembly for a file
src/shallow-blue-fork/src/transptable.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/transptable.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/transptable.cc.s
.PHONY : src/shallow-blue-fork/src/transptable.cc.s

src/shallow-blue-fork/src/uci.o: src/shallow-blue-fork/src/uci.cc.o

.PHONY : src/shallow-blue-fork/src/uci.o

# target to build an object file
src/shallow-blue-fork/src/uci.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/uci.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/uci.cc.o
.PHONY : src/shallow-blue-fork/src/uci.cc.o

src/shallow-blue-fork/src/uci.i: src/shallow-blue-fork/src/uci.cc.i

.PHONY : src/shallow-blue-fork/src/uci.i

# target to preprocess a source file
src/shallow-blue-fork/src/uci.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/uci.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/uci.cc.i
.PHONY : src/shallow-blue-fork/src/uci.cc.i

src/shallow-blue-fork/src/uci.s: src/shallow-blue-fork/src/uci.cc.s

.PHONY : src/shallow-blue-fork/src/uci.s

# target to generate assembly for a file
src/shallow-blue-fork/src/uci.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/uci.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/uci.cc.s
.PHONY : src/shallow-blue-fork/src/uci.cc.s

src/shallow-blue-fork/src/zkey.o: src/shallow-blue-fork/src/zkey.cc.o

.PHONY : src/shallow-blue-fork/src/zkey.o

# target to build an object file
src/shallow-blue-fork/src/zkey.cc.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/zkey.cc.o
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/zkey.cc.o
.PHONY : src/shallow-blue-fork/src/zkey.cc.o

src/shallow-blue-fork/src/zkey.i: src/shallow-blue-fork/src/zkey.cc.i

.PHONY : src/shallow-blue-fork/src/zkey.i

# target to preprocess a source file
src/shallow-blue-fork/src/zkey.cc.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/zkey.cc.i
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/zkey.cc.i
.PHONY : src/shallow-blue-fork/src/zkey.cc.i

src/shallow-blue-fork/src/zkey.s: src/shallow-blue-fork/src/zkey.cc.s

.PHONY : src/shallow-blue-fork/src/zkey.s

# target to generate assembly for a file
src/shallow-blue-fork/src/zkey.cc.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/shallow-blue-fork/src/zkey.cc.s
	$(MAKE) -f CMakeFiles/chess-engine.dir/build.make CMakeFiles/chess-engine.dir/src/shallow-blue-fork/src/zkey.cc.s
.PHONY : src/shallow-blue-fork/src/zkey.cc.s

src/tests/chess_engine_tests.o: src/tests/chess_engine_tests.cpp.o

.PHONY : src/tests/chess_engine_tests.o

# target to build an object file
src/tests/chess_engine_tests.cpp.o:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/tests/chess_engine_tests.cpp.o
.PHONY : src/tests/chess_engine_tests.cpp.o

src/tests/chess_engine_tests.i: src/tests/chess_engine_tests.cpp.i

.PHONY : src/tests/chess_engine_tests.i

# target to preprocess a source file
src/tests/chess_engine_tests.cpp.i:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/tests/chess_engine_tests.cpp.i
.PHONY : src/tests/chess_engine_tests.cpp.i

src/tests/chess_engine_tests.s: src/tests/chess_engine_tests.cpp.s

.PHONY : src/tests/chess_engine_tests.s

# target to generate assembly for a file
src/tests/chess_engine_tests.cpp.s:
	$(MAKE) -f CMakeFiles/chess-engine-test.dir/build.make CMakeFiles/chess-engine-test.dir/src/tests/chess_engine_tests.cpp.s
.PHONY : src/tests/chess_engine_tests.cpp.s

src/tests/tiny_osc_tests.o: src/tests/tiny_osc_tests.cpp.o

.PHONY : src/tests/tiny_osc_tests.o

# target to build an object file
src/tests/tiny_osc_tests.cpp.o:
	$(MAKE) -f CMakeFiles/tiny-osc-test.dir/build.make CMakeFiles/tiny-osc-test.dir/src/tests/tiny_osc_tests.cpp.o
.PHONY : src/tests/tiny_osc_tests.cpp.o

src/tests/tiny_osc_tests.i: src/tests/tiny_osc_tests.cpp.i

.PHONY : src/tests/tiny_osc_tests.i

# target to preprocess a source file
src/tests/tiny_osc_tests.cpp.i:
	$(MAKE) -f CMakeFiles/tiny-osc-test.dir/build.make CMakeFiles/tiny-osc-test.dir/src/tests/tiny_osc_tests.cpp.i
.PHONY : src/tests/tiny_osc_tests.cpp.i

src/tests/tiny_osc_tests.s: src/tests/tiny_osc_tests.cpp.s

.PHONY : src/tests/tiny_osc_tests.s

# target to generate assembly for a file
src/tests/tiny_osc_tests.cpp.s:
	$(MAKE) -f CMakeFiles/tiny-osc-test.dir/build.make CMakeFiles/tiny-osc-test.dir/src/tests/tiny_osc_tests.cpp.s
.PHONY : src/tests/tiny_osc_tests.cpp.s

src/tinyosc/tinyosc.o: src/tinyosc/tinyosc.c.o

.PHONY : src/tinyosc/tinyosc.o

# target to build an object file
src/tinyosc/tinyosc.c.o:
	$(MAKE) -f CMakeFiles/tiny_osc.dir/build.make CMakeFiles/tiny_osc.dir/src/tinyosc/tinyosc.c.o
.PHONY : src/tinyosc/tinyosc.c.o

src/tinyosc/tinyosc.i: src/tinyosc/tinyosc.c.i

.PHONY : src/tinyosc/tinyosc.i

# target to preprocess a source file
src/tinyosc/tinyosc.c.i:
	$(MAKE) -f CMakeFiles/tiny_osc.dir/build.make CMakeFiles/tiny_osc.dir/src/tinyosc/tinyosc.c.i
.PHONY : src/tinyosc/tinyosc.c.i

src/tinyosc/tinyosc.s: src/tinyosc/tinyosc.c.s

.PHONY : src/tinyosc/tinyosc.s

# target to generate assembly for a file
src/tinyosc/tinyosc.c.s:
	$(MAKE) -f CMakeFiles/tiny_osc.dir/build.make CMakeFiles/tiny_osc.dir/src/tinyosc/tinyosc.c.s
.PHONY : src/tinyosc/tinyosc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... chess-engine-test"
	@echo "... test"
	@echo "... chess-engine"
	@echo "... tiny-osc-test"
	@echo "... tiny_osc"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shallow-blue-fork/src/attacks.o"
	@echo "... src/shallow-blue-fork/src/attacks.i"
	@echo "... src/shallow-blue-fork/src/attacks.s"
	@echo "... src/shallow-blue-fork/src/board.o"
	@echo "... src/shallow-blue-fork/src/board.i"
	@echo "... src/shallow-blue-fork/src/board.s"
	@echo "... src/shallow-blue-fork/src/book.o"
	@echo "... src/shallow-blue-fork/src/book.i"
	@echo "... src/shallow-blue-fork/src/book.s"
	@echo "... src/shallow-blue-fork/src/eval.o"
	@echo "... src/shallow-blue-fork/src/eval.i"
	@echo "... src/shallow-blue-fork/src/eval.s"
	@echo "... src/shallow-blue-fork/src/generalmovepicker.o"
	@echo "... src/shallow-blue-fork/src/generalmovepicker.i"
	@echo "... src/shallow-blue-fork/src/generalmovepicker.s"
	@echo "... src/shallow-blue-fork/src/main.o"
	@echo "... src/shallow-blue-fork/src/main.i"
	@echo "... src/shallow-blue-fork/src/main.s"
	@echo "... src/shallow-blue-fork/src/move.o"
	@echo "... src/shallow-blue-fork/src/move.i"
	@echo "... src/shallow-blue-fork/src/move.s"
	@echo "... src/shallow-blue-fork/src/movegen.o"
	@echo "... src/shallow-blue-fork/src/movegen.i"
	@echo "... src/shallow-blue-fork/src/movegen.s"
	@echo "... src/shallow-blue-fork/src/movepicker.o"
	@echo "... src/shallow-blue-fork/src/movepicker.i"
	@echo "... src/shallow-blue-fork/src/movepicker.s"
	@echo "... src/shallow-blue-fork/src/option.o"
	@echo "... src/shallow-blue-fork/src/option.i"
	@echo "... src/shallow-blue-fork/src/option.s"
	@echo "... src/shallow-blue-fork/src/orderinginfo.o"
	@echo "... src/shallow-blue-fork/src/orderinginfo.i"
	@echo "... src/shallow-blue-fork/src/orderinginfo.s"
	@echo "... src/shallow-blue-fork/src/pawnstructuretable.o"
	@echo "... src/shallow-blue-fork/src/pawnstructuretable.i"
	@echo "... src/shallow-blue-fork/src/pawnstructuretable.s"
	@echo "... src/shallow-blue-fork/src/psquaretable.o"
	@echo "... src/shallow-blue-fork/src/psquaretable.i"
	@echo "... src/shallow-blue-fork/src/psquaretable.s"
	@echo "... src/shallow-blue-fork/src/qsearchmovepicker.o"
	@echo "... src/shallow-blue-fork/src/qsearchmovepicker.i"
	@echo "... src/shallow-blue-fork/src/qsearchmovepicker.s"
	@echo "... src/shallow-blue-fork/src/rays.o"
	@echo "... src/shallow-blue-fork/src/rays.i"
	@echo "... src/shallow-blue-fork/src/rays.s"
	@echo "... src/shallow-blue-fork/src/search.o"
	@echo "... src/shallow-blue-fork/src/search.i"
	@echo "... src/shallow-blue-fork/src/search.s"
	@echo "... src/shallow-blue-fork/src/transptable.o"
	@echo "... src/shallow-blue-fork/src/transptable.i"
	@echo "... src/shallow-blue-fork/src/transptable.s"
	@echo "... src/shallow-blue-fork/src/uci.o"
	@echo "... src/shallow-blue-fork/src/uci.i"
	@echo "... src/shallow-blue-fork/src/uci.s"
	@echo "... src/shallow-blue-fork/src/zkey.o"
	@echo "... src/shallow-blue-fork/src/zkey.i"
	@echo "... src/shallow-blue-fork/src/zkey.s"
	@echo "... src/tests/chess_engine_tests.o"
	@echo "... src/tests/chess_engine_tests.i"
	@echo "... src/tests/chess_engine_tests.s"
	@echo "... src/tests/tiny_osc_tests.o"
	@echo "... src/tests/tiny_osc_tests.i"
	@echo "... src/tests/tiny_osc_tests.s"
	@echo "... src/tinyosc/tinyosc.o"
	@echo "... src/tinyosc/tinyosc.i"
	@echo "... src/tinyosc/tinyosc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

