#!/bin/bash

echo "preinstalling: gtk+-x11-3.0, webkit2gtk-4.0, freeglut3-dev, libasound2-dev, libfreetype6-dev, libjack-dev, libx11-dev, libxcomposite-dev, libxcursor-dev, libxinerama-dev, mesa-common-dev, libcurl4-openssl-dev"

sudo apt-get install gtk+-x11-3.0 webkit2gtk-4.0 freeglut3-dev libasound2-dev libfreetype6-dev libjack-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev mesa-common-dev libcurl4-openssl-dev

